on: push
jobs:
  last-job:
    runs-on: macos-latest
    steps:
      - run: node --version
      - run: npm --versions
      - uses: actions/checkout@v3
      - run: npm ci
      - run: node index.js
      - run: npx eslint .
